declare const styles: {
    container: string;
    toolbar: string;
    titleBlock: string;
    chartTitle: string;
    controls: string;
    search: string;
    zoomControls: string;
    scrollArea: string;
    tree: string;
    nodeWrapper: string;
    card: string;
    rootCard: string;
    name: string;
    title: string;
    dept: string;
    initials: string;
    avatar: string;
    info: string;
    toggle: string;
    expanded: string;
    children: string;
    connector: string;
    childRow: string;
    state: string;
    spinner: string;
    spin: string;
    errorIcon: string;
    hint: string;
};
export default styles;
//# sourceMappingURL=OrgChart.module.scss.d.ts.map